### ISSUE TITLE
JOSS REVIEW - tests don't cover all code functionalities promised in the paper

### ISSUE THREAD

**Issue by elena-pascal** [utpal-singh/SAnTex#11]
This relates to https://github.com/openjournals/joss-reviews/issues/6886

Since you differentiate between 5 functionalities the code can offer, I would expect tests that cover at least parts of each of these.

**Comment by hakonanes** [comment]
The test in *tests/test.py* won't run due to incorrect imports:

```python
$ python tests/test.py 
Traceback (most recent call last):
  File "/Users/hakon/kode/personal/SAnTex/tests/test.py", line 3, in <module>
    from santex import Material, Anisotropy, Tensor, Isotropy
ImportError: cannot import name 'Material' from 'santex' (/opt/homebrew/Caskroom/miniforge/base/envs/stx-env/lib/python3.12/site-packages/santex/__init__.py)
```

MacOS, Python 3.12, SAnTex 1.2.2.

**Comment by utpal-singh** [comment]
> The test in _tests/test.py_ won't run due to incorrect imports:
> 
> $ python tests/test.py 
> Traceback (most recent call last):
>   File "/Users/hakon/kode/personal/SAnTex/tests/test.py", line 3, in <module>
>     from santex import Material, Anisotropy, Tensor, Isotropy
> ImportError: cannot import name 'Material' from 'santex' (/opt/homebrew/Caskroom/miniforge/base/envs/stx-env/lib/python3.12/site-packages/santex/__init__.py)
> MacOS, Python 3.12, SAnTex 1.2.2.

Thank you for pointing this out. The issue comes from incorrect imports in tests/test.py in the previous version of SanTex. The issue is now resolved
